### PR TITLE
Update openapi.yaml

### PR DESCRIPTION
**Pull request by nieny225**
- Resolved the conflict in the schema where a string from the enum was not matching due to a oneOf constraint issue.

### CODE REVIEW

**Comment by athyuttamre** [comment]
This is intentional in our schema, so that generated SDKs can support both a list of known models and a backup `string` value that allows passing other models. What's the error or issue you are facing as a result?

**Comment by nieny225** [comment]
@athyuttamre thanks for your response! If so, should it be anyOf instead of oneOf? As it currently stands, any string from the enum will satisfy both conditions, which seems to be in conflict with the exclusive nature of oneOf.

**Comment by athyuttamre** [comment]
Good point, let me look into this!

**Comment by athyuttamre** [comment]
This is now fixed: https://github.com/openai/openai-openapi/pull/54

**Pull request closed without merging**
